apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8000         # Nginx가 접근할 포트
      targetPort: 8000   # Flask 컨테이너의 포트
  type: ClusterIP
